server:
  port: 8081
  shutdown: graceful

spring:
  ## 기본은 test로 설정
  profiles:
    active: test

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    show-sql: true

feign:
  okhttp:
    enabled: true
  autoconfiguration:
    jackson:
      enabled: true