server:
  shutdown: graceful
  port: 8082

spring:
  profiles:
    active: test

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  redis:
    host: localhost
    port: 6379


feign:
  client:
    url:
      user-api: 'localhost:8081'