name: githubActionTest
on:
  push:
    branches : [ main ]

# defaults:
#  run:
#    shell: bash
#    working-directory: batch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Open Web Client Directory
        run: |
          ls -la
